name: Release Maven

# author Mrxn
# github: github.com/Mr-xn

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: "Liberica"
          java-version: 1.8
          java-package: jdk+fx
      - name: Build with Maven
        run:
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release-name: SPATool${{github.ref}}
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE}}

      - name: Auto Upload Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE}}
        with:
          upload_url: ${{ step.release.upload_url }}
          asset_path: ./SPATool-${{ github.ref }}.jar
          asset_name: SPATool-${{ github.ref }}.jar
          asset_content_type: application/java-archive


      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: # optional, default is artifact
            SPATool
          # A file, directory or wildcard pattern that describes what to upload
          path:
            target/*.jar
          # The desired behavior if no files are found using the provided path.
          prerelease: false
          draft: false
